services:
  app:
    image: todo-font-dev
    build:
        context: ./todo-frontend #this directory will be the build context
        dockerfile: ./todo-frontend/dev.Dockerfile
    volumes:
        - ./todo-frontend:/usr/src/app
        - node_modules:/usr/src/app/node_modules
    ports:
        - 5173:5173
    container_name: todo-front-dev

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-todo
    depends_on:
      - app # wait for the frontend container to be started

volumes:
  node_modules: