services:
  app:
    image: todo-font
    build:
        context: ./todo-frontend #this directory will be the build context
        dockerfile: Dockerfile
    volumes:
        - ./todo-frontend:/usr/src/app
        - node_modules:/usr/src/app/node_modules
    container_name: todo-front

  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database

    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    container_name: mongo

  redis:
    image: redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD
    volumes:
      - ./todo-backend/redis_data:/data
    container_name: redis

  server:
    image: todo-back
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    container_name: todo-back

  nginx:
    image: nginx:1.29.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-todo
    depends_on:
      - app # wait for the frontend container to be started
      - server # wait for the backend container

volumes:
  node_modules: